[build]
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/messages/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
